In [1]:
import pandas as pd

pd.read_parquet("/Users/almazbaktygali/Desktop/data-annotation-aiym/data/test/parquets/elarna_hs_0to20467_0.parquet")

,path,hand_label,frame,x1,y1,x2,y2,x3,y3,x4,...,x17,y17,x18,y18,x19,y19,x20,y20,x21,y21
0,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Right,19,-0.030567,0.010715,-0.058977,0.034392,-0.083847,0.053601,-0.101834,...,0.016508,0.089409,0.013739,0.117583,0.009728,0.136134,0.004921,0.151343,NaN,NaN
1,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Right,20,-0.030221,0.010297,-0.058691,0.033762,-0.084462,0.053362,-0.103696,...,0.013782,0.089768,0.010439,0.117802,0.006012,0.136695,0.001042,0.152235,NaN,NaN
2,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Right,30,0.014032,-0.041519,0.048063,-0.069079,0.071830,-0.085022,0.088939,...,0.122580,0.011372,0.147695,0.002236,0.141233,-0.005293,0.130331,-0.007295,NaN,NaN
3,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Right,31,0.025958,-0.037383,0.065697,-0.064086,0.092357,-0.085358,0.109012,...,0.125908,0.013605,0.166990,0.013877,0.160559,0.008281,0.145900,0.005176,NaN,NaN
4,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Right,32,0.025656,-0.037395,0.065792,-0.063265,0.093253,-0.082846,0.111066,...,0.125560,0.013344,0.167057,0.013814,0.161216,0.008218,0.146986,0.005186,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20462,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Right,15675,0.022076,-0.033611,0.059243,-0.056295,0.093962,-0.061340,0.120356,...,0.075997,-0.040030,0.116283,-0.036346,0.114104,-0.025320,0.102970,-0.018646,NaN,NaN
20463,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Right,15676,0.018270,-0.030982,0.057368,-0.051966,0.093260,-0.055358,0.120679,...,0.074471,-0.037070,0.111886,-0.032556,0.107328,-0.021554,0.094728,-0.015951,NaN,NaN
20464,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Right,15677,0.018844,-0.030698,0.064427,-0.048990,0.104426,-0.050227,0.134051,...,0.067234,-0.023865,0.114130,-0.016218,0.105509,-0.006942,0.088148,-0.006347,NaN,NaN
20465,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Right,15678,0.020640,-0.030134,0.063645,-0.050049,0.101861,-0.055764,0.128180,...,0.060608,-0.017149,0.089121,-0.005024,0.080663,0.001230,0.066012,0.001260,NaN,NaN
20466,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Right,15679,0.021233,-0.030163,0.064581,-0.050010,0.102821,-0.055700,0.129346,...,0.060008,-0.017450,0.090103,-0.004934,0.081794,0.001486,0.066877,0.001330,NaN,NaN

In [2]:
pd.read_parquet("/Users/almazbaktygali/Desktop/data-annotation-aiym/data/test/parquets/elarna_hs_0to21042_0.parquet")

,path,hand_label,frame,x1,y1,x2,y2,x3,y3,x4,...,x17,y17,x18,y18,x19,y19,x20,y20,x21,y21
0,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Right,36,0.026572,-0.034467,0.073608,-0.056017,0.111379,-0.060558,0.140804,...,0.089157,-0.009869,0.131268,-0.009519,0.158088,-0.007294,0.179864,-0.004492,NaN,NaN
1,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Right,37,0.016653,-0.031879,0.051226,-0.058644,0.075552,-0.074405,0.096378,...,0.091744,0.009563,0.128052,0.011616,0.152009,0.014092,0.172690,0.017400,NaN,NaN
2,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Right,38,0.018681,-0.034935,0.056096,-0.060417,0.082315,-0.078705,0.096977,...,0.101726,0.016433,0.136968,0.023862,0.160081,0.028630,0.179790,0.033079,NaN,NaN
3,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Left,38,-0.025676,-0.032801,-0.070252,-0.054336,-0.102926,-0.071829,-0.124446,...,-0.087985,0.018214,-0.124665,0.026721,-0.130245,0.031735,-0.130725,0.035377,NaN,NaN
4,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Left,39,-0.032385,-0.033026,-0.077358,-0.062229,-0.105917,-0.084074,-0.124798,...,-0.095174,-0.000778,-0.126643,0.004739,-0.143388,0.011403,-0.157197,0.016425,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21037,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Left,14816,-0.057264,0.012808,-0.097232,0.049637,-0.107123,0.088645,-0.094926,...,-0.014378,0.106250,-0.023921,0.134404,-0.020085,0.125949,-0.014312,0.112865,NaN,NaN
21038,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Right,14817,0.057711,0.006017,0.106748,0.042226,0.131808,0.077491,0.144357,...,0.017802,0.100607,0.029639,0.136647,0.037648,0.153849,0.041171,0.164809,NaN,NaN
21039,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Left,14817,-0.045904,0.027702,-0.080530,0.075993,-0.092586,0.117144,-0.086027,...,-0.005787,0.094439,-0.015942,0.139969,-0.013732,0.154863,-0.010858,0.162094,NaN,NaN
21040,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Left,14818,-0.045911,0.029709,-0.079986,0.079018,-0.092081,0.120333,-0.085463,...,-0.009188,0.097164,-0.018404,0.144642,-0.014203,0.158613,-0.009858,0.164298,NaN,NaN
21041,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Left,14819,-0.043264,0.025594,-0.073537,0.069540,-0.081058,0.109610,-0.073671,...,-0.011202,0.082940,-0.014945,0.126560,-0.009198,0.140472,-0.005024,0.146880,NaN,NaN

In [3]:
pd.read_parquet("/Users/almazbaktygali/Desktop/data-annotation-aiym/data/test/parquets/elarna_hs_0to50000_0.parquet")

,path,hand_label,frame,x1,y1,x2,y2,x3,y3,x4,...,x17,y17,x18,y18,x19,y19,x20,y20,x21,y21
0,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Right,36,0.026572,-0.034467,0.073608,-0.056017,0.111379,-0.060558,0.140804,...,0.089157,-0.009869,0.131268,-0.009519,0.158088,-0.007294,0.179864,-0.004492,NaN,NaN
1,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Right,37,0.016653,-0.031879,0.051226,-0.058644,0.075552,-0.074405,0.096378,...,0.091744,0.009563,0.128052,0.011616,0.152009,0.014092,0.172690,0.017400,NaN,NaN
2,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Right,38,0.018681,-0.034935,0.056096,-0.060417,0.082315,-0.078705,0.096977,...,0.101726,0.016433,0.136968,0.023862,0.160081,0.028630,0.179790,0.033079,NaN,NaN
3,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Left,38,-0.025676,-0.032801,-0.070252,-0.054336,-0.102926,-0.071829,-0.124446,...,-0.087985,0.018214,-0.124665,0.026721,-0.130245,0.031735,-0.130725,0.035377,NaN,NaN
4,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Left,39,-0.032385,-0.033026,-0.077358,-0.062229,-0.105917,-0.084074,-0.124798,...,-0.095174,-0.000778,-0.126643,0.004739,-0.143388,0.011403,-0.157197,0.016425,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Left,5206,-0.006116,-0.038884,0.009923,-0.075843,0.034219,-0.098828,0.054720,...,0.074692,-0.060137,0.091155,-0.084856,0.091204,-0.096664,0.091143,-0.103000,NaN,NaN
49996,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Left,5207,-0.018745,-0.033283,-0.048624,-0.049720,-0.066905,-0.062748,-0.068339,...,-0.102148,0.021817,-0.139180,0.033506,-0.161898,0.042045,-0.181140,0.050305,NaN,NaN
49997,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Left,5207,-0.007426,-0.031448,-0.003854,-0.066647,0.004500,-0.092430,0.017686,...,0.068346,-0.063815,0.080994,-0.087047,0.082493,-0.096636,0.084842,-0.103259,NaN,NaN
49998,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Left,5208,-0.017867,-0.032767,-0.045813,-0.049258,-0.065700,-0.063158,-0.067173,...,-0.104051,0.024089,-0.139598,0.033699,-0.160801,0.041262,-0.178266,0.048780,NaN,NaN
49999,/Volumes/T7/elarna/elarna_video_sorted_2020_20...,Right,5208,0.004162,-0.018149,0.009965,-0.044630,0.016282,-0.072015,0.027491,...,0.055779,-0.076245,0.068123,-0.099050,0.064604,-0.105959,0.060935,-0.108130,NaN,NaN